In [2]:
import numpy as np
def solve(dimensions,value):
    return np.full(dimensions,value)
result=solve((3,3),5)
print(result)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [3]:
import numpy as np

def sumarrays(*arrays):
    return np.sum(arrays, axis=0)
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])

result = sumarrays(a, b, c)
print(result)

[[15 18]
 [21 24]]


In [4]:
import numpy as np

def top_left_sub_matrix(matrix, N, M):
    return matrix[:N, :M]
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = top_left_sub_matrix(matrix, 2, 2)
print(result)

[[1 2]
 [4 5]]


In [8]:
import numpy as np
def bottom_right(matrix,N,M):
    return matrix[-N:,-M:]
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]])
result=bottom_right(matrix,2,2)
print(result)

[[5 6]
 [8 9]]


In [11]:
import numpy as np

def solution(arr):
    return {
        'mean': float(np.mean(arr)),
        'std_dev': float(np.std(arr))}
arr = np.array([1, 1, 1])
result = solution(arr)
print(result)

{'mean': 1.0, 'std_dev': 0.0}
